WITH CTE AS(SELECT NUM,LEAD(NUM) OVER(ORDER BY ID) AS [AFTER],LAG(NUM) OVER(ORDER BY ID) AS [BEFORE]FROM LOGS)
	SELECT distinct NUM AS ConsecutiveNums FROM CTEWHERE [AFTER] = NUM AND [BEFORE] = NUM;
